### PR TITLE
add dynamodb table sbeacon-dataportal-user-quota

### PR DESCRIPTION
**Pull request by froghiey**
dynamodb additional table to save information sagemaker usage for every user

### CODE REVIEW

**Comment by XTIDfdenni** [comment]
cc: @anuradhawick @NickEdwards7502

**Comment by devopsxti** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Failed**: This project is currently locked by an unapplied plan from pull #7. To continue, delete the lock from #7 or apply that plan and merge the pull request.

Once the lock is released, comment `atlantis plan` here to re-plan.

**Comment by devopsxti** [comment]
**Plan Error**
```
the default workspace at path . is currently locked by another command that is running for this pull request.
Wait until the previous command is complete and try again
```

**Comment by devopsxti** [comment]
**Plan Error**
```
the default workspace at path . is currently locked by another command that is running for this pull request.
Wait until the previous command is complete and try again
```

**Pull request merged**
